on:
  push:
    branches:
      - main

name: ðŸš€ Deploy backend on push

jobs:
  backend-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest

    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: ðŸ”¨ Install dependencies
        run: npm install

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_NODE_SERVER }}
          username: ${{ secrets.GIT_CPANEL_NODE_USER }}
          password: ${{ secrets.GIT_CPANEL_NODE_PWD }}
          protocol: ${{ secrets.GIT_CPANEL_NODE_PROTOCOL }}
          local-dir: ./
